name: Readme

on:
  issues:
    types: [opened, edited]
  workflow_dispatch:

jobs:
  readme:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
        ref: ${{ github.head_ref }}
    - run:  'echo "$ISSUE_BODY" > temp.txt'
      env: 
        ISSUE_BODY: ${{ github.event.issue.body }}
    - name: Set up Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: 2.6.5
    - name: Bundle install
      run: |
        bundle install --jobs 4 --retry 3
    - name: create-readme
      run: |
        bundle exec ruby create-readme.rb
        rm temp.txt
    - name: Create Pull Request
      if: ${{ startsWith(github.event.issue.title, 'Add handle') }}
      uses: peter-evans/create-pull-request@v3.5.0
      with:
        commit-message: ${{ github.event.issue.title }}
        title: ${{ github.event.issue.title }}
        body: |
          Closes #${{ github.event.issue.number }}
        labels: automated pr
        branch: add-new-developer-${{ github.event.issue.number }}
